/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ReviewerService } from "../reviewer.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ReviewerCreateInput } from "./ReviewerCreateInput";
import { Reviewer } from "./Reviewer";
import { ReviewerFindManyArgs } from "./ReviewerFindManyArgs";
import { ReviewerWhereUniqueInput } from "./ReviewerWhereUniqueInput";
import { ReviewerUpdateInput } from "./ReviewerUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ReviewerControllerBase {
  constructor(
    protected readonly service: ReviewerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Reviewer })
  @nestAccessControl.UseRoles({
    resource: "Reviewer",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createReviewer(
    @common.Body() data: ReviewerCreateInput
  ): Promise<Reviewer> {
    return await this.service.createReviewer({
      data: data,
      select: {
        createdAt: true,
        email: true,
        id: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Reviewer] })
  @ApiNestedQuery(ReviewerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Reviewer",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reviewers(@common.Req() request: Request): Promise<Reviewer[]> {
    const args = plainToClass(ReviewerFindManyArgs, request.query);
    return this.service.reviewers({
      ...args,
      select: {
        createdAt: true,
        email: true,
        id: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Reviewer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reviewer",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reviewer(
    @common.Param() params: ReviewerWhereUniqueInput
  ): Promise<Reviewer | null> {
    const result = await this.service.reviewer({
      where: params,
      select: {
        createdAt: true,
        email: true,
        id: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Reviewer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reviewer",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateReviewer(
    @common.Param() params: ReviewerWhereUniqueInput,
    @common.Body() data: ReviewerUpdateInput
  ): Promise<Reviewer | null> {
    try {
      return await this.service.updateReviewer({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          id: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Reviewer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reviewer",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteReviewer(
    @common.Param() params: ReviewerWhereUniqueInput
  ): Promise<Reviewer | null> {
    try {
      return await this.service.deleteReviewer({
        where: params,
        select: {
          createdAt: true,
          email: true,
          id: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
